/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.lang.Math;
import java.util.Scanner;


public class App {

    public static void main(String[] args) {
        convertTemp converter = null;

        Scanner scanner = new Scanner(System.in);

        System.out.println("Bem vindo!");
        System.out.println("Insira a opção de conversão: ");
        System.out.println("1. Fahrenheit ");
        System.out.println("2. Celsius \n");

        int opcao = scanner.nextInt();

        System.out.println("Insira a temperatura para converter: \n");

        int temperatura = scanner.nextInt();;

        if (opcao == 1){
            converter = new convertTempToFahrenheit();
            double result = converter.convertTemp(temperatura);
            System.out.println("A temperatura " + temperatura + " convertida para Fahrenheit é aproximadamente: " + Math.round(result));
        } else if (opcao == 2){
            converter = new convertTempToCelsius();
            double result = converter.convertTemp(temperatura);
            System.out.println("A temperatura " + temperatura + " convertida para Celsius é aproximadamente: " + Math.round(result));
        } else {
            System.out.println("Opção inválida. Tente novamente");
        }

        scanner.close();
    }
}
